spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sampledb
    username: user
    password: user
  cache:
    jcache:
      config: classpath:ehcache.xml